### ISSUE TITLE
Broken notes widget on Android 

### ISSUE THREAD

**Issue by baldarn** [nextcloud/notes-android#2123] opened 2024-04-02 19:31 UTC
after update the note widget is not working 

## Steps to reproduce
1. use the widget on android

### Expected behaviour
the widget should work

### Actual behaviour
crashes

### app log
```
App Version: 4.2.0
App Version Code: 40020090
App Flavor: fdroid

Files App Version Code: 30280190 (PROD)

---

OS Version: 5.15.104-android13-3-27760517(A546BXXS6BXC1)
OS API Level: 34
Device: a54x
Manufacturer: samsung
Model (and Product): SM-A546B (a54xnaeea)

---

java.lang.RuntimeException: Unable to start receiver it.niedermann.owncloud.notes.widget.notelist.NoteListWidget: java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4905)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2498)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3073)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:7021)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:561)
	at android.app.PendingIntent.getActivity(PendingIntent.java:537)
	at android.app.PendingIntent.getActivity(PendingIntent.java:501)
	at it.niedermann.owncloud.notes.widget.notelist.NoteListWidget.updateAppWidget(NoteListWidget.java:44)
	at it.niedermann.owncloud.notes.widget.notelist.NoteListWidget.onReceive(NoteListWidget.java:75)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4896)
	... 9 more

```

## Server
Please complete the following information.

- Notes app version: 
- Nextcloud version: 
- OS: 
- Web server: 
- PHP version: 
- Database: 

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: 

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by pawlowskatze** [comment] 2024-04-09 09:42
Same here since last update
- on the phone side:
  - Android 14
  - Notes Android App version 4.2.0
- on the NC Hub side:
  - NC Hub 28.0.4
  - Notes App on Hub is version 4.9.4

**Comment by willitcode** [comment] 2024-04-09 17:48
Same issue here. I have stacktraces and any other relevant information available, please feel free to contact me.

**Comment by baldarn** [comment] 2024-04-10 12:17
I try to open a PR. I don't know how to try/test this :/

https://github.com/nextcloud/notes-android/pull/2130

**Comment by strugee** [comment] 2024-04-12 22:48
Duplicate of #2091

**Closed by strugee** 2024-04-12 22:48 UTC
Labels: bug
