### ISSUE TITLE
Syncing issues on Samsung Galaxy Android 12

### ISSUE THREAD

**Issue by landowark** [nextcloud/notes-android#1518] opened 2022-05-07 12:51 UTC
I'm having a real problem with syncing the app with my nextcloud instance, getting the following error:

````
App Version: 3.4.19
App Version Code: 3004019
App Flavor: play

Files App Version Code: 30200190

---

OS Version: 4.19.113-23725773(G986WVLU2FVC5)
OS API Level: 31
Device: y2q
Manufacturer: samsung
Model (and Product): SM-G986W (y2qcsw)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.UnknownErrorException: Read timed out
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: com.nextcloud.android.sso.exceptions.UnknownErrorException: Read timed out
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more
```

I've tried clearing the cache and data, re-installing the app and it will sync everything that had been added up to that point, but not any new notes.

**Comment by stefan-niedermann** [comment] 2022-05-07 14:32
Hello 👋 sorry for the inconveniences ans thank you very much for the 2★ rating 🙂 Quite motivating to provide support *after* such a review.

Did you already read our [FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#unknownerrorexception-read-timed-out) regarding this specific error?

**Comment by landowark** [comment] 2022-05-07 16:14
I'm having the opposite problem that the FAQ describes. The initial sync goes flawlessly while any subsequent notes  trigger this error. I've just tried removing my larger folders and doing a reinitialization, success. I added in a single note with the text "this is just a test". and I get the timeout error.

**Comment by stefan-niedermann** [comment] 2022-05-11 06:31
- How many notes do you have in total?
- Which size does an average note have?
- Which size do all your notes have in total?
- What internet connection do you have? 2G / 3G / 4G / Wi-Fi and which speed?
- Which hardware are you using on your Nextcloud server?

A "Read timeout" basically is caused by a slow server or a response that took too long. After the initial import however, only a delta is synchronized (only the changed data is transferred), why it is a bit odd, that you get the exception *after* an import.

Do you also get the error message when adding a note on your Android device rather than on the web interface?

**Comment by landowark** [comment] 2022-05-12 01:21
Hi, thanks for getting back to me.

- I have about 800 notes in total.
- Most of them are <1kb, but a few can get up to 100kb.
- Total size is 4.5Mb (There are some media attachments adding in with Qownnotes that I'm not counting).
- I've been trying to sync on both 4G and Wi-Fi (speeds of about 90Mbps).
- My Nextcloud is hosted in a docker container on my synology NAS (INTEL Celeron J4125, 8GB of RAM)

I'm doubtful that it's a connection or hardware issue, unless there's some kind of issue with the docker container, but I can access the notes api fine using Postman on my laptop. 
I do also get the message when I add a note on my device as well as on the web interface.

**Comment by stefan-niedermann** [comment] 2022-05-13 08:03
Thanks for the specs - the technical specs look absolutely fine so far.

Let me clearly state, that this is a *note* taking app and not a word processor. A file with 100kb means a 30 Din A4 pages document, which is *not* my definition of a "note". Consider splitting them up to smaller files, maybe within a subfolder as such huge files will also have impact on the rendering speed when you are viewing and editing the contents on your Android device.

Could you please try moving all your notes to another folder (as you already did), synchronize with the Notes Android app. Then adding one or two notes back to the folder in batches (always synchronozing between the chunks).

When do you reach the point where the issue appears when you create a new note via the web UI? Especially put the huge notes separatly, not all at once.

PS.: Of course we can skip at any point if you are tired of testing and refund the money you paied at the Play Store (let me know) - though I am curious to find the exact cause of the issue given ten thousands of users did never report the described behavior you are experiencing, nor am I able to reproduce the issue locally.

**Comment by joshtrichards** [comment] 2024-09-10 17:34
Closing due to no response after >2 years and not really anything actionable here remains in our side.

**Closed by joshtrichards** 2024-09-10 17:34 UTC
