### ISSUE TITLE
Attach apk file to GitHub Releases

### ISSUE THREAD

**Issue by rusty-snake** [nextcloud/notes-android#1957] opened 2023-12-17 13:12 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

---

https://github.com/nextcloud/android has apks attached to github releases but https://github.com/nextcloud/notes-android not.

**Comment by stefan-niedermann** [comment] 2023-12-17 13:38
Duplicate of https://github.com/nextcloud/notes-android/issues/1884

Please use the 🔍  **search function** before opening new issues.

**Closed by stefan-niedermann** 2023-12-17 13:38 UTC

**Comment by rusty-snake** [comment] 2023-12-17 13:46
I searched for "apk" and "apk release". Both did not found #1884. A searching for "Obtainium" would had found it.

Since 4.0.0 and 4.1.0 are created as Releases the title of #1884 is a bit misleading if it is still open to track apk attachments.

**Comment by stefan-niedermann** [comment] 2023-12-17 14:05
`releases` was what i searched for and given it is still open, that's enough in my opinion, but you can add a comment to #1884 if you want. Two open issues regarding GitHub Releases are unnecessary in my opinion.
