### ISSUE TITLE
Multiple instances of application in Recent Apps

### ISSUE THREAD

**Issue by jpmv27** [nextcloud/notes-android#2151] opened 2024-04-22 19:19 UTC
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Open the Notes app
2. Open a note
3. Tap the Recent Apps button (three vertical bars)
4. There are two instances of the Notes app, one with the main menu, and one with the open note

### Expected behavior

Until recently, there would only be a single instance of the Notes app in the Recent Apps.
It is unclear whether this was an intentional or accidental change.
I did not see anything in the release notes referring to this, although I did not examine every commit in detail.

(While creating this issue, I noticed that after opening the About dialog, there are now three instances in the Recent Apps)

### Notes Android version

4.2.1

### Notes server version

4.9.4

### Nextcloud Android version

3.28.2

### Nextcloud version

27.1.8

### Device

Samsung Galaxy A32 5G

### Android Version

13

### App Store

- [X] Google Play Store
- [ ] F-Droid
- [ ] Huawei App Gallery

**Comment by JonasMayerDev** [comment] 2024-04-29 19:47
Dupe of https://github.com/nextcloud/notes-android/issues/2124

**Closed by JonasMayerDev** 2024-04-29 19:47 UTC
Labels: bug
