### ISSUE TITLE
Nextcloud Collectives App

### ISSUE THREAD

**Issue by pschopen** [nextcloud/notes-android#1818] opened 2023-06-15 18:02 UTC
Maybe it would make sense to take the work from Nextcloud Notes and use it for a Nextcloud Collectives App? Editing and storing .MD-Files would be the same and only the folder structure would need any change?

**Comment by stefan-niedermann** [comment] 2023-06-15 18:44
Please use the 🔍  **search function** before opening new issues.

Closing as duplicate of https://github.com/nextcloud/notes-android/issues/1658

**Closed by stefan-niedermann** 2023-06-15 18:44 UTC

**Comment by pschopen** [comment] 2023-06-15 19:09
Are there any plans in that regard?
