### ISSUE TITLE
java.lang.IllegalStateException: Duplicate key 285468811 (attempted merging values 284 and 286)

### ISSUE THREAD

**Issue by marek22k** [nextcloud/notes-android#2053] opened 2024-03-08 13:37 UTC
Hello,

I'm having some problems with the Nextcloud Notes app:
My notes are not always syncing properly. When I edit them on the computer, the notes are not always on the smartphone.
Furthermore, empty notes often appear that I have not even created. It also sometimes happens that notes appear twice.
In addition, I constantly receive the following error message:

```
App Version: 4.1.0
App Version Code: 40010090
App Flavor: fdroid

Files App Version Code: 30280090 (PROD)

---

OS Version: 4.19.306-perf(24504010)
OS API Level: 34
Device: FP4
Manufacturer: Fairphone
Model (and Product): FP4 (FP4eea)

---

java.lang.IllegalStateException: Duplicate key 285468811 (attempted merging values 284 and 286)
	at java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.util.stream.Collectors$$ExternalSyntheticLambda39.accept(Unknown Source:6)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1642)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:503)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:519)
	at it.niedermann.owncloud.notes.persistence.NotesRepository.getIdMap(NotesRepository.java:463)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:208)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by strugee** [comment] 2024-04-12 23:07
Duplicate of #1914

**Closed by strugee** 2024-04-12 23:07 UTC
