### ISSUE TITLE
Conflict resolution failing, newer server changes overwritten

### ISSUE THREAD

**Issue by cheywood** [nextcloud/notes-android#1846] opened 2023-07-19 04:28 UTC
**Describe the bug**

There's something wrong with the usage of the conflict detection elements of the API. It's possible to lose content that's already been updated on the server through the Android app overwriting those changes.

**To Reproduce**
1. Create a note using the web app
2. Ensure that note gets synced to the Android app
3. Enable Airplane Mode on the phone
4. Make an addition to the note in the web app
5. Make an addition to the note in the Android app
6. Disable Airplane Mode on the phone and allow sync to complete
7. Reload the note in the web app and see that the edits made in step 4 have been overwritten

I think I swiped away the app and restarted between steps 5 and 6 but I'm not sure that matters. I've been seeing this for some time.

**Expected behavior**

It shouldn't be possible to blindly overwrite changes on the server with local content. There should be a sync conflict which is handled. The API works as expected.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 4.1.0 RC1 (but have been seeing for some time)
 - F-Droid or Play Store: F-Droid
 - Android-Version: 13
 - Device: Pixel 6a (GrapheneOS)

**Server**
 - Nextcloud version: 26.0.3
 - Nextcloud Notes version (server app): 4.8.0

**Comment by SeanDS** [comment] 2023-09-10 10:21
I've had this issue as well for a long time and I've lost data this way several times. I just had it again today on notes 4.8.1 and notes-android 4.1.0 RC1.

**Comment by calidancer** [comment] 2024-04-08 09:51
Hi Team,
This issue is still happening.
Lately I have the impression that a lot of complains for issues or feature requests remain unheard and completely ignored.
I'm sure you are busy dealing with more important stuff, however this issue is not to be ignored. It's been 6 months since the last comment above and not even an acknowledgment is made. If you guys behave like that, your solution will loose credibility.

This is a small list of issues / feature requests still open for a long time and unresolved:

- https://github.com/nextcloud/talk-android/issues/2704
- https://github.com/nextcloud/deck/issues/5539

Can you please fix this issue with Nextcloud Notes?

Thanks.

**Comment by jancborchardt** [comment] 2024-09-09 09:34
FYI @juliushaertl @stefan-niedermann since it’s a data loss issue.

@calidancer just to be clear – Nextcloud is an open source community project, everyone is very welcome to contribute. :)

**Comment by stefan-niedermann** [comment] 2024-09-09 10:17
Basically a duplicate of https://github.com/nextcloud/notes-android/issues/161

I'd recommend to close this in favor of the original issue. The title of #161 suggest to prevent editing, but it's actually a possible intermediate step to an actual conflict resolution.

"Last change wins" has been the mode since existence of the Notes app, actual conflict resolution is a huge amount of work h korelstar actually put quite some time in analysing what would need to be done - https://github.com/nextcloud/notes-android/issues/161#issuecomment-444443403

**Comment by jancborchardt** [comment] 2024-09-09 13:36
Thanks for the explanation @stefan-niedermann! Closing this in favor of https://github.com/nextcloud/notes-android/issues/161 then as you said. :)

**Closed by jancborchardt** 2024-09-09 13:36 UTC
Labels: bug
