### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by karol-exe** [nextcloud/notes-android#2469] opened 2024-11-06 23:50 UTC
### Is your feature request related to a problem? Please describe.

Certainly, here’s a suggestion:

---

I would like to share some feedback regarding the categories for notes. While I find them helpful, I believe the system would be even more effective with the addition of tags. Tags would provide more flexibility, allowing notes to be organized across multiple themes or topics rather than being restricted to one category. This change could make finding and grouping related notes quicker and more intuitive. 

Thank you for considering this improvement!

### Describe the solution you'd like

Pls add #tags in notes.

**Comment by joshtrichards** [comment] 2024-11-12 21:45
Duplicate of nextcloud/notes#299

**Closed by joshtrichards** 2024-11-12 21:45 UTC
Labels: enhancement
